### ISSUE TITLE
Provide step by step on how do I get started and get to the first successful food log starting from a brand new SwiftUI app

### ISSUE THREAD

**Issue by drstarson** [Passiolife/Passio-Nutrition-AI-iOS-SDK-Distribution#37]
- [ ] Provide step by step on how do I get started and get to the first successful food log starting from a brand new SwiftUI app

**Comment by marinPassio** [comment]
@Pratik7u Please add a link to the [Quick start guide](https://passio.gitbook.io/nutrition-ai/guides/ios-sdk-docs/quick-start-guide) in the readme of the distribution repo

**Comment by Pratik7u** [comment]
I have added the link to the Quick start project and updated the steps
@drstarson We haven't yet created any demo using `SwiftUI`, whatever we have created is using `UIKit`
